name: Deploy Vite app to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Verify Node.js and npm
        run: |
          node -v
          npm -v

      - name: Install dependencies
        run: npm ci

      - name: Fix Vite permissions
        run: chmod +x ./node_modules/.bin/vite

      - name: Build Vite project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v6
        with:
          branch: gh-pages
          folder: dist
          clean: true
